<a id=toc></a>
# Table of Content
1. [Basics](#section1)

[Ref](https://www.youtube.com/playlist?list=PLqnslRFeH2UqLwzS0AwKDKLrpYBKzLBy2)

## Collections -> counter, namedTuple, orderedDict, defaultDict, deque

In [1]:
from collections import Counter

In [18]:
ch = 'aaaaabbbbcc'
count = Counter(ch)
print(count)
print(count.most_common(1))
print(count.keys())

Counter({'a': 5, 'b': 4, 'c': 2})
[('a', 5)]
dict_keys(['a', 'b', 'c'])


In [19]:
from collections import namedtuple

In [28]:
Point = namedtuple('Point', ['x','y'])
pt = Point(2,3)
print(pt)
print(pt.x,pt.y)

Point(x=2, y=3)
2 3


In [29]:
from collections import OrderedDict

In [30]:
ordered_dict = OrderedDict()
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['a'] = 1
print(ordered_dict)

OrderedDict([('b', 2), ('c', 3), ('d', 4), ('a', 1)])


In [36]:
from collections import defaultdict
import random

In [48]:
default_dict = defaultdict(int)
# default_dict = defaultdict(lambda:random.randint(0,10))
# default_dict = defaultdict(lambda:'vanilla')
default_dict['a'] = 1
default_dict['b'] = 2
print(default_dict)
print(default_dict['c'])

defaultdict(<class 'int'>, {'a': 1, 'b': 2})
0


In [49]:
from collections import deque

In [81]:
#Its a double ended list where you can insert and delete items from start/end
de = deque()
de.append(2)
de.append(3)
de.appendleft(1)
print(de)
de.extendleft([4,5,6])
print(de)
de.popleft()
print(de)
de.rotate(2) # circular buffer
print(de)
de.rotate(-2)
print(de)

deque([1, 2, 3])
deque([6, 5, 4, 1, 2, 3])
deque([5, 4, 1, 2, 3])
deque([2, 3, 5, 4, 1])
deque([5, 4, 1, 2, 3])


## Itertools -> product, permutations, combinations, accumulate, groupby, infinite iterator

In [54]:
from itertools import product

In [58]:
a = [1,3]
b = [2,4]
prod = product(a,b)
# prod = product(a,b, repeat=2)
print(list(prod))

[(1, 2), (1, 4), (3, 2), (3, 4)]


In [59]:
from itertools import permutations

In [66]:
a = [1,2,3]
# perm = permutations(a)
perm = permutations(a, 2)
print(list(perm))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [71]:
from itertools import combinations, combinations_with_replacement

In [73]:
a = [1,2,3,4]
comb = combinations(a, 2)
print(list(comb))
comb_wr = combinations_with_replacement(a, 2)
print(list(comb_wr))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


In [82]:
from itertools import accumulate
import operator

In [86]:
a = [1,2,3,4]
acc = accumulate(a)
print(a)
print(list(acc))

# You can also multiply
acc = accumulate(a, func=operator.mul)
print(list(acc))

# You can also use custom function
a = [1,2,5,3,4]
acc = accumulate(a, func=max)
print(list(acc))

[1, 2, 3, 4]
[1, 3, 6, 10]
[1, 2, 6, 24]
[1, 2, 5, 5, 5]


In [87]:
from itertools import groupby

In [110]:
a = [1,2,3,4]
# You can groupby condition or function
def less_than_3(x):
    return x < 3

group_obj = groupby(a, key=less_than_3)
# group_obj = groupby(a, key=lambda x:x<4)
for a,b in group_obj:
    print(a, list(b))
    
# You can work on data like pandas
persons = [{'name':'Tim', 'age':25},{'name':'lisa', 'age':25},
          {'name':'andre', 'age':29},{'name':'john', 'age':27}]

person_by_age = groupby(persons, key=lambda x: x['age'])
for a,b in person_by_age:
    print(a, list(b))

True [1, 2]
False [3, 4]
25 [{'name': 'Tim', 'age': 25}, {'name': 'lisa', 'age': 25}]
29 [{'name': 'andre', 'age': 29}]
27 [{'name': 'john', 'age': 27}]


In [111]:
from itertools import count, cycle, repeat

In [113]:
# Infinite Iterators

## Count
for i in count(10):
    print(i)
    if i == 15:
        break

10
11
12
13
14
15


In [118]:
## Cycle
a = [1,2,3] 
b=0
for i in cycle(a):
    print(i)
    b += 1
    if b == 10:
        break

1
2
3
1
2
3
1
2
3
1


In [120]:
for i in repeat(1.5, 5):
    print(i)

1.5
1.5
1.5
1.5
1.5


## Lambda, Map, Filter, Reduce

In [124]:
points2D = [(1,2),(15,1),(5,-1),(10,4)]
print(points2D)

# sort according to 1st element
points2D_sorted = sorted(points2D)
print(points2D_sorted)

# sort according to 2nd element
points2D_sorted = sorted(points2D, key=lambda x: x[1])
print(points2D_sorted)

# sort given the sum of x and y
points2D_sorted = sorted(points2D, key=lambda x: x[0] + x[1])
print(points2D_sorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]
[(5, -1), (15, 1), (1, 2), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [126]:
# map(func, seq)
a = [1,2,3,4,5]

b = map(lambda x: x*2, a)
print(list(b))

[2, 4, 6, 8, 10]


In [127]:
# filter(func, seq)
a = [1,2,3,4,5]

b = filter(lambda x: x%2==0, a)
print(list(b))

[2, 4]


In [130]:
# reduce(func, seq)
from functools import reduce

a = [1,2,3,4]

product_a = reduce(lambda x,y: x*y, a)
print(product_a)

sum_a = reduce(lambda x,y: x+y, a)
print(sum_a)

24
10


## Errors and Exception

In [144]:
## Name Error 
# a = c

## Type Error 
# a = 5 + '10'

## Value Error
# a = [1,2,3]
# a.remove(4)

## Syntax Error
# print a

## NotFoundError
# import somemodule
# file = open('somefile.txt')

## Index Error
# a = [1,2,3]
# a[4]

## Key Error
# my_dict = {'name': 'Tim'}
# my_dict['age']

In [145]:
# Raise Exception
x = -5

if x < 0:
    raise Exception('x should be positive')

Exception: x should be positive

In [146]:
# Assert
x = -5

assert(x>=0), "x is not positive"

AssertionError: x is not positive

In [147]:
# Catch or Handle Exception
try:
    x = 5/0
except:
    print('an error happened')

an error happened


In [153]:
# Catch or Handle Exception
try:
    x = 5/0
except Exception as e:
    print(e)
else:
    print('No error')
finally:
    print("cleaning up...")

division by zero
cleaning up...


In [163]:
# Define your own exception class with inherit base class 'Exception'
class ValueTooHighError(Exception):
    pass

class ValueTooLowError(Exception):
    def __init__(self, message, value):
        self.message = message
        self.value = value

def test_value(x):
    if x > 100:
        raise ValueTooHighError('value is too high')
    if x < 5:
        raise ValueTooLowError('value is too low', x)

# test_value(200)

try:
    test_value(1)
# except Exception as e:
#     print(e)
except ValueTooLowError as e:
    print(e.message, e.value)

value is too low 1


## Random Numbers

In [165]:
import random

In [169]:
# float random between 0 to 1
a = random.random()
print(a)

# float random between custom range
a = random.uniform(1,10)
print(a)

# int random between custom range (includes upper bound)
a = random.randint(1,10)
print(a)

# int random between custom range (excludes upper bound)
a = random.randrange(1,10)
print(a)

0.9679615842420137
3.237200848391711
5
1


In [186]:
# normal distribution random with mean=0 and std_dev=1
a = random.normalvariate(0,1)
print(a)

1.4607093712612038


In [204]:
# list random or sequence random
my_list = list('ABCDEFG')
mylist = list('ABCDEFG')

a = random.choice(my_list)
print(a)

# sample values non-unique/repeat_is_okay
a = random.choices(my_list, k=3)
print(a)

# sample unique values
a = random.sample(my_list, 3)
print(a)

# random shuffle list inplace
print(mylist)
random.shuffle(mylist)
print(mylist)

B
['C', 'G', 'F']
['D', 'F', 'B']
['A', 'B', 'C', 'D', 'E', 'F', 'G']
['E', 'B', 'D', 'G', 'C', 'F', 'A']


In [205]:
# Reproducible random
random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(1) #call seed again to reproduce
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2


In [229]:
# Cryptographically secure random numbers
import secrets

# int rand from 0 to excluded upperbound
a = secrets.randbelow(10)
print(a)

# generate random k bits
a = secrets.randbits(4)
print(bin(a))

# list or sequence random
my_list = list('ABCDEFG')
a = secrets.choice(my_list)
print(a)

4
0b100
B


In [238]:
# Numpy random module for arrays and matrices
import numpy as np

# ndarray of float random values between 0 to 1
a = np.random.rand(3,3)
print(a)

# ndarray of random int (upperbound excluded)
a = np.random.randint(0,10, (3,4))
print(a)

# array random row shuffle (shuffle only 1st dimension)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
np.random.shuffle(a)
print(a)

[[0.1575358  0.77628206 0.24473665]
 [0.10539768 0.08092898 0.11317986]
 [0.93332668 0.24837528 0.60881576]]
[[2 4 1 3]
 [8 2 9 5]
 [6 6 9 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


## Decorators, Generators, others pending

## On line Progress Bar with tqdm

In [4]:
from tqdm import tqdm, trange
import time

In [3]:
for i in tqdm([1,2,3,4,5]):
    time.sleep(0.5)

100%|██████████| 5/5 [00:02<00:00,  1.99it/s]


In [5]:
for i in trange(10):
    time.sleep(0.5)

100%|██████████| 10/10 [00:05<00:00,  1.99it/s]


In [7]:
pbar = tqdm(total=100)
for i in range(10):
    time.sleep(0.5)
    pbar.update(10)
pbar.close()

100%|██████████| 100/100 [00:05<00:00, 19.91it/s]


In [6]:
with tqdm(total=100) as pbar:
    for i in range(10):
        time.sleep(0.5)
        pbar.update(10)

100%|██████████| 100/100 [00:05<00:00, 19.91it/s]
